### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by clarkio** [clarkio/house-bot#1]
- [ ] Add minion bee doh bee doh animation to be triggered when there's a new follower
- [ ] Add light effect for donations via streamelements API
- [ ] Integrate with the Philips Hue lights as well
- [ ] Trigger sending commands by emote
